### ISSUE TITLE
Ajuste por cambio de modelo de datos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/acta_recibido_crud#1]
Se debe generar un ajuste en la API CRUD debido a un cambio en el modelo de datos del modulo de acta de recibido
- [x] Cambio de modelos
- [x] Swagger
- [x] Logs
- [x] Refactor
- [ ] Beego Migrations

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/acta_recibido_crud/commit/f26c974face77cd5f1a36f304bd04cc0a3ebc319 
Modificacion de modelos

https://github.com/udistrital/acta_recibido_crud/commit/23dbf0baab790fc2fcc8d3b2ced86087e3a5b9bc
Creacion de logs

https://github.com/udistrital/acta_recibido_crud/commit/8429a1924f487873f44b74e884dc6c77543da3e9
Refactor

**Comment by mafeave** [comment]
De la revisión realizada al API, se debe ajustar lo siguiente:
- Definir las variables de configuración en el archivo config.js, tomar de ejemplo: [config](https://github.com/udistrital/produccion_academica_crud/blob/produccion_academica/conf/app.conf), ajustar la ruta de conexión en el main.
- Ajustar las rutas de los modelos en los controladores, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/acta_recibido_crud/models"
- Ajustar la ruta del directorio de los controladores en router.go, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/acta_recibido_crud/controllers"
- Ajustar la ruta de los routers en main.go, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/acta_recibido_crud/routers"
- Ajustar nombre del bin generado en el .gitignore
- Generar de nuevo la documentación del API para actualizar las rutas generadas en swagger

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/acta_recibido_crud/commit/94455c3a0b6593cebd06d959245568530e14ccbf

- [ ] actualizacion del README.md con la configuracion de las variables de entorno

- [ ] configuracion de los items del comentario anterior
