### ISSUE TITLE
Pruebas Unitarias API CRUD

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/acta_recibido_crud#15]
se deben generar pruebas unitarias para las tablas parametricas a la respectiva API

- [x] estado_acta

- [x] estado_elemento

- [x] tipo_bien

**Comment by ManuelMurillo** [comment]
se muestran las pruebas generadas para las tablas parametricas
estado_acta
![prueba_estado_acta](https://user-images.githubusercontent.com/29108085/68051937-8d840e00-fcb6-11e9-9695-6da29884f59f.png)
estado_elemento
![prueba_estado_elemento](https://user-images.githubusercontent.com/29108085/68051945-8fe66800-fcb6-11e9-89ae-d5df09e7676d.png)
tipo_bien
![prueba_tipo_bien](https://user-images.githubusercontent.com/29108085/68051950-9248c200-fcb6-11e9-9a31-b6483d41db9f.png)

**Comment by mafeave** [comment]
Se verifican las pruebas realizadas, se hacer merge a las ramas dev y test del API
