### ISSUE TITLE
Desligar Elementos de los Soportes

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/acta_recibido_crud#60]
De lo mencionado en [reunión del 3 de Marzo](https://drive.google.com/file/d/1CLqny1i7UzFKJEuoJD5ejcv42di9BcOf/view), y concluído en contrataciones previas; que cada API tenga sus elementos desconoce que Arka en Si es un sistema no solamente para registrar los procedimientos de Almacen sino que debió de pensarse también para el control de inventarios.

Previendo lo anterior (la creación de una API dedicada para los elementos, que en sí serían el inventario, en torno al cual todo el desarrollo debería estar orientado), se plantea lo siguiente:

- [x] Cambiar el modelo de tal manera que los elementos no estén asociados al soporte sino al acta
- [x] Cambiar el modelo de tal manera que el proveedor (y otros campos que sean susceptibles de ser cambiados durante el flujo de aprobación del acta) esté asociado al ~~acta~~ historico_acta y no al soporte.
- [x] Socializar cambios con Jhon y/o DBAs
- [x] ~~Ajustar las migraciones~~
- [x] Identificar los cambios implicados en esta y otras APIs
- [x] Identificar los cambios implicados en las peticiones que realiza el cliente
- [x] ~~Aplicar los cambios identificados~~
- [x] #61 

Los tachados se harán en otro(s) Issue(s) una vez se estime el orden y tiempo necesario para los ajustes

**Comment by ludwinggsanchez** [comment]
Para dar cumplimiento a las nuevas consideraciones, se propone el siguiente modelo:

![acta_recibido_v6](https://user-images.githubusercontent.com/35748918/127428550-4a63cbf8-b66c-4284-a310-6df639387441.png)

Los cambios son los siguientes:

1. Tabla elemento:
- Borrar constraint key fk_elemento_soporte_acta
- Borrar columna soporte_acta_id
- Crear columna acta_recibido_id
- Crear constraint key fk_elemento_acta_recibido
- Borrar columna verificado ya que esta información ya existe en fk_elemento_estado_elemento

2. Tabla soporte_acta
- Borrar columna proveedor_id
Nota: Si se quiere hacer seguimiento a los soportes, se debería cambiar el fk_soporte_acta_acta_recibido a fk_soporte_acta_historico_acta

3. Tabla historico_acta
- Crear columna proveedor_id
- Crear columna ubicacion_id
- Crear columna revisor_id
- Crear columna persona_asignada_id
- Crear columna observaciones
- Crear columna fecha_visto_bueno

4. Tabla acta_recibido
- Crear columna tipo_acta_id
- Borrar columna ubicacion_id
- Borrar columna revisor_id
- Borrar columna persona_asignada
- Borrar columna observaciones
- Borrar columna fecha_visto_bueno
- Crear constraint key fk_tipo_acta

5. Tabla tipo_acta
- Crear Tabla
- Crear  columna id
- Crear columna nombre
- Crear columna descripcion
- Crear columna codigo_abreviacion
- Crear columna activo
- Crear columna fecha_modificacion
- Crear columna fecha_creacion
- Crear sequencia tipo_acta_id_seq
- Crear constraint key pk_tipo_acta
- Insertar valores paramétricos

**Comment by ludwinggsanchez** [comment]
### Cambios api acta_recibido_crud

Ajustar odelos:
- acta_recibido
- historico_acta
- elemento
- soporte_acta
- transaccion_acta_recibido
- transaccion_soporte_acta

Crear modelo

- tipo_acta

Ajustar transacciones

**Comment by ludwinggsanchez** [comment]
### Cambios api arka_mid

Además de actualizar los modelos, se deben actualizar las siguientes funciones:

1. actaRecibidoHelper:
- GetAllActasRecibidoActivas()
- GetElementos(actaId)

Tiempo estimado: 1-2 días

**Comment by ludwinggsanchez** [comment]
### Cambios arka_cliente

Registro acta/Registro de acta especial:
- Actualizar la construcción de la transacción para hacer el post del acta
Edición acta: 
- Actualizar función Cargar_Formularios(transaccion)
- Actualizar la construcción de la transacción para hacer el put del acta
Consulta actas:
- Actualizar función anularActa para que la transacción quede correcta
Ver detalle:
- Actualizar función Cargar_Formularios(transaccion)
Verificación acta:
- Actualizar función Cargar_Formularios(transaccion)
- Actualizar la construcción de la transacción para hacer el put del acta

Tiempo estimado: 1-2 días

**Comment by AlexFBP** [comment]
De acuerdo a lo sugerido, identificar los cambios necesarios para #61 sin ejecutar los ajustes todavía.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
