### ISSUE TITLE
Parametrizar tipo de Acta

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/acta_recibido_crud#61]
**Considerando:**

> Adicionalmente, se presentan los siguientes inconvenientes a nivel de modelo de datos en el api acta_recibido_crud:
>
> 1. Tabla acta_recibido: 
>
> - Columna ubicacion_id: Se deben permitir valores nulos.
> - Columna acta_especial: Se requiere agregar esta nueva columna dado que por este guardado temporal ya no hay manera de identificar las actas especiales, por lo que el modelo quedaría como sigue:
>
> ![acta_recibido_v5](https://user-images.githubusercontent.com/35748918/126114526-05b2064c-3d5f-4b19-a634-85ba8e2ac9f4.png)
>
_Originally posted by @ludwinggsanchez in https://github.com/udistrital/arka_cliente/issues/645#issuecomment-882284013_

> Lo anterior debe revisarse con John y/o DBAs
> 
> Adicional/Complementariamente; en vez de agregarse una columna de Acta Especial, podría considerarse en vez de un booleano, una clave foranea de una nueva tabla "tipoActa". A los IDs de esta nueva tabla adicionalmente podrían vincularse los tipos de entrada que se pueden asociar y así se podría, por un lado, dejar de trabajar con estos valores "quemados", y por otro lado, facilitaría considerar el desarrollo de la parte paramétrica relacionada con esta gestión

_Originally posted by @AlexFBP in https://github.com/udistrital/arka_cliente/issues/645#issuecomment-882591098_

**Realizar:**

- [x] Agregar tabla tipo_acta al modelo(*)
- [x] Agregar tipo_acta_id a la tabla de acta(*)
- [x] Socializar con DBAs y/o Jhon(*)
- [x] Realizar ajustes a esta API
- [x] Actualizar las peticiones relacionadas, del MID
- [x] Actualizar las peticiones relacionadas, del Cliente

(*) se desarrollarán en #60

Entrega estimada: 07/sep/21

**Comment by ludwinggsanchez** [comment]
Se propone que los cambios de este issue se unifiquen con #60

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
